import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import {
  Box,
  Container,
  Grid,
  GridItem,
  Heading,
  Text,
} from "@chakra-ui/react";
import TeamCard from "../components/TeamCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>Team - MINeD 2023 Hackathon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW={"container.xl"} marginInline="auto">
        <Navbar />
        <Box marginBlock={16}>
          <Heading paddingBlock={8} textAlign={["center", "left"]}>
            Meet Our Team
          </Heading>
          <Heading
            size={"lg"}
            color={"blue.400"}
            textAlign={["center", "left"]}
            paddingBlock={4}
          >
            Mentors
          </Heading>
          <TeamGrid />
          <Heading
            size={"lg"}
            color={"blue.400"}
            textAlign={["center", "left"]}
            paddingBlock={4}
          >
            Developers
          </Heading>
          <DeveloperGrid />
        </Box>
        <Footer />
      </Container>
    </>
  );
}

function TeamGrid() {
  return (
    <Grid
      h="auto"
      templateRows={{ sm: "repeat(8, 1fr)", md: "repeat(2, 1fr)" }}
      templateColumns={{ sm: "repeat(1, 1fr)", md: "repeat(4, 1fr)" }}
      gap={4}
      marginBottom={8}
    >
      <GridItem>
        <TeamCard
          url={"image url"}
          name={"Raj Patel"}
          description={"This is some kind of description"}
          link={"link for linkedin"}
        />
      </GridItem>
      <GridItem>
        <TeamCard
          url={"image url"}
          name={"Raj Patel"}
          description={"This is some kind of description"}
          link={"link for linkedin"}
        />
      </GridItem>
      <GridItem>
        <TeamCard
          url={"image url"}
          name={"Raj Patel"}
          description={"This is some kind of description"}
          link={"link for linkedin"}
        />
      </GridItem>
      <GridItem>
        <TeamCard
          url={"image url"}
          name={"Raj Patel"}
          description={"This is some kind of description"}
          link={"link for linkedin"}
        />
      </GridItem>
      <GridItem>
        <TeamCard
          url={"image url"}
          name={"Raj Patel"}
          description={"This is some kind of description"}
          link={"link for linkedin"}
        />
      </GridItem>
    </Grid>
  );
}

function DeveloperGrid() {
  return (
    <Grid
      h="auto"
      templateRows={{ sm: "repeat(8, 1fr)", md: "repeat(2, 1fr)" }}
      templateColumns={{ sm: "repeat(1, 1fr)", md: "repeat(4, 1fr)" }}
      gap={4}
      marginBottom={8}
    >
      <GridItem>
        <TeamCard
          url={"image url"}
          name={"Raj Patel"}
          description={"This is some kind of description"}
          link={"link for linkedin"}
        />
      </GridItem>
      <GridItem>
        <TeamCard
          url={"image url"}
          name={"Raj Patel"}
          description={"This is some kind of description"}
          link={"link for linkedin"}
        />
      </GridItem>
      <GridItem>
        <TeamCard
          url={"image url"}
          name={"Raj Patel"}
          description={"This is some kind of description"}
          link={"link for linkedin"}
        />
      </GridItem>
      <GridItem>
        <TeamCard
          url={"image url"}
          name={"Raj Patel"}
          description={"This is some kind of description"}
          link={"link for linkedin"}
        />
      </GridItem>
      <GridItem>
        <TeamCard
          url={"image url"}
          name={"Raj Patel"}
          description={"This is some kind of description"}
          link={"link for linkedin"}
        />
      </GridItem>
    </Grid>
  );
}
